services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma-demo
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data
    environment:
      - ANONYMIZED_TELEMETRY=FALSE

  chroma-admin:
    image: fengzhichao/chromadb-admin
    container_name: chroma-admin
    ports:
      - "3001:3001"
    environment:
      - CHROMA_API_URL=http://chroma:8000
    depends_on:
      - chroma

volumes:
  chroma-data:
